### ISSUE TITLE
Test script name

### ISSUE THREAD

**Issue by Keithbsmiley** [thoughtbot/liftoff#155]
Using the [current default](https://github.com/thoughtbot/liftoff/blob/f5e7468dfe50dbdb3d04ad58aec336d4786e08d5/defaults/liftoffrc#L24) `bin/test` [this gem](https://github.com/thoughtbot/dotfiles/blob/7dbc8f44a15b768f1dddb4f60b46a851b7f10764/zshrc#L72-L73):

```
# mkdir .git/safe in the root of repositories you trust
export PATH=".git/safe/../../bin:$PATH"
```

Does not work with test since the shell command overrides the executable so running `test` attempts to use zsh's version. Obviously `setup` works just fine. Thoughts on an option to have this work?

**Comment by gfontenot** [comment]
I'm going to close this. It occurs to me that you could change this yourself by overriding the templates key in your personal `.liftoffrc`
