### ISSUE TITLE
Project template

### ISSUE THREAD

**Issue by pardnoj** [thoughtbot/liftoff#186]
I created .liftoffrc file in my ~/Developer/iOS directory and when I run liftoff command in this directory, it creates swift project but I declared

project_template: objc

in my .liftoffrc configuration file.

EDIT:
liftoff --template objc seems to work.

**Comment by gfontenot** [comment]
@pardnoj Any update?

**Comment by gfontenot** [comment]
I'm closing this due to lack of info/activity. If you have any new info, please feel free to reopen.
