### ISSUE TITLE
[Feature] Change build settings (`extra_config`) in UnitTests target too

### ISSUE THREAD

**Issue by AliSoftware** [thoughtbot/liftoff#193]
Hi @gfontenot 

I wanted to change specific Build Settings in my Unit Tests target (namely remove `TEST_HOST` and `BUNDLE_LOADER` build settings to set empty values, so that my CI don't try to launch the simulator and fail, whereas I don't have any application test but only functional ones)

Using `extra_config` only changes Build Settings of the App Target. It would be great to have a `tests_extra_config` or something similar for the Unit Tests Target too.

**Comment by gfontenot** [comment]
Implementing this with #213

**Comment by AliSoftware** [comment]
:+1: :tada:
