### ISSUE TITLE
Install with `gem`

### ISSUE THREAD

**Issue by AliSoftware** [thoughtbot/liftoff#200]
Please restore the possibility to install `liftoff` using `gem`.
### Rationale
- `gem` is installed with the system in OSX. There is no need to install additional tools to make it work
- `homebrew` needs administrator provileges. This is bad. Some machines (in particular in a corporate environment) don't have it, and thus can't install. (Whereas `gem` can install in a `$GEM_HOME` located in `$HOME/gems` for example, that does not need any admin privileges)
- Homebrew makes the installation process more complex for those who want to dig in right away. We need to search for Homebrew on the internet for those who don't know it yet to know how to install it, then go back to liftoff to install it… installing a tool to install a tool is kinda too much meta :smile: and discourage some users.

Requiring admin privileges in the main problem here, but having to install a tool to install another is just as discouraging.

**Comment by Pitometsu** [comment]
Hi there, I use *macports*, so installing homebrew will make a mash from my OS X. Is it possible to install it not from brew?

**Comment by gfontenot** [comment]
@Pitometsu As noted above, you can always install it manually using the tarballs in the releases tab. I'm not planning on officially supporting any other automated installation methods, though.
