### ISSUE TITLE
[Feature] Allow to specify ordering of build phases

### ISSUE THREAD

**Issue by bitcrumb** [thoughtbot/liftoff#204]
While experimenting with my own template setup, I needed to be able to insert a build phase at a specific point. More specifically before the 'Copy Bundle Resources' phase (since it was a script that would modify some app icons & overlay it with some text).

Would this be an addition that others would find useful as well? Not too sure yet how I would go about this (especially configuration-wise), but it certainly should be doable.

**Comment by gfontenot** [comment]
This is in master with 98814ec
