### ISSUE TITLE
Something doesn't work

### ISSUE THREAD

**Issue by frootloops** [thoughtbot/liftoff#215]
When I run liftoff in a empty directory I get error "Could not find an Xcode project file. You need to run me from a valid project directory."
![screen shot 2015-03-01 at 00 12 48](https://cloud.githubusercontent.com/assets/861670/6428169/bb953aea-bfa7-11e4-9129-90e7a6c87e8a.png)
![screen shot 2015-03-01 at 00 13 44](https://cloud.githubusercontent.com/assets/861670/6428172/dfb74cba-bfa7-11e4-9d7e-412ebb25f6a6.png)
![screen shot 2015-03-01 at 00 13 52](https://cloud.githubusercontent.com/assets/861670/6428173/dfbdad4e-bfa7-11e4-88b1-1215b5982ca9.png)

Is it my fault?

**Comment by gfontenot** [comment]
You're using an incredibly (over 1 year) old version of Liftoff. Uninstall that version (`gem uninstall liftoff`) and install the version from Homebrew as outlined [in the README](https://github.com/thoughtbot/liftoff#installation)
