### ISSUE TITLE
Can't generate a zipfile in default template 

### ISSUE THREAD

**Issue by Dronaldo17** [thoughtbot/liftoff#217]
liftoff 1.4.1 when I fix the default template and add an zipfile ，it runs error，please look the pictures 
![qq20150310-1 2x](https://cloud.githubusercontent.com/assets/4099574/6570425/331a2cf8-c735-11e4-91df-877381b68cb9.png)
![qq20150310-2 2x](https://cloud.githubusercontent.com/assets/4099574/6570475/f9adb4ac-c735-11e4-933a-68b18c0a99b3.png)
![qq20150310-3 2x](https://cloud.githubusercontent.com/assets/4099574/6570480/0edcd74a-c736-11e4-9fe8-faf5a489e780.png)

**Comment by gfontenot** [comment]
Liftoff doesn't know what to do with that zip file because it's trying to run it through the templating library. Why do you need to add a zip file to all of your projects? What do you expect to happen here?

**Comment by Dronaldo17** [comment]
3ks,got it!
