### ISSUE TITLE
Specifying frameworks and libraries to link against

### ISSUE THREAD

**Issue by allewun** [thoughtbot/liftoff#219]
Is it beyond the scope of `liftoff` to have this configuration ability? For example, I'd like to link against a `.framework` file and some `.dylib` files.

**Comment by gfontenot** [comment]
Not sure what you're asking specifically. If you want to link against system frameworks, you can do that through he `extra_config` key. If you want to bring in third party frameworks, that's probably better handled with a dependency management system like Carthage or CocoaPods.

**Comment by allewun** [comment]
@gfontenot `extra_config` looks promising, but it seems that the keys specified there are only applied under the .pbxproj's `buildSettings` section. If you add a binary such as `libsqlite3.dylib` to link with, you'll notice that the project file touches several other areas.

Thanks for your other suggestion, I think that's the way to go.
