### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by marlowcharite** [thoughtbot/liftoff#230]
I'm having trouble tracking this down but seems to be that I cannot build a project initialized and started by liftoff with carthage frameworks. That is to say that libraries linked through carthage instead of cocoa pods seem to result in the invocation error. Any word on this? I didn't see anyone else having issues with it but did see an issue for documenting carthage support.

**Comment by gfontenot** [comment]
I think I noticed yesterday that our unit test bundles don't have the run path search paths configured properly, but I haven't had time to confirm. They should look like this (you should be able to copy/paste this into the settings editor):

```
//:configuration = Debug
LD_RUNPATH_SEARCH_PATHS = $(inherited) @executable_path/Frameworks @loader_path/Frameworks

//:configuration = Release
LD_RUNPATH_SEARCH_PATHS = $(inherited) @executable_path/Frameworks @loader_path/Frameworks

//:completeSettings = some
LD_RUNPATH_SEARCH_PATHS
```

Let me know if that helps, and we can work on adding a fix.

**Comment by marlowcharite** [comment]
@gfontenot I'll take a look when I get a chance and let you know. Thanks

**Comment by marlowcharite** [comment]
Forgot to write back...sorry. Unfortunately that didn't work

**Comment by gfontenot** [comment]
I'll need more info on what the failure is.

**Comment by marlowcharite** [comment]
@gfontenot I apologize, forgot to follow up. Looks like dragging frameworks built by carthage didn't also add the path to `/Carthage/Build/iOS/` under framework search paths in build settings.

**Comment by gfontenot** [comment]
Ah, good to hear. Sorry you were having problems.
