### ISSUE TITLE
Storyboards and XIBs are added to "Compile Sources" build phase

### ISSUE THREAD

**Issue by marcelofabri** [thoughtbot/liftoff#231]
When creating a project, Storyboards and XIBs are added to "Compile Sources" build phase, which makes `xcodebuild` to fail sometimes on the command `CompileStoryboard`.

To fix the issue, I manually moved them to the "Copy Build Resources" phase and I've never seen this issue again. (As suggested on [this](http://stackoverflow.com/a/30664590/1777634) SO answer)

**Comment by marcelofabri** [comment]
I think we only need to add `xib` and `storyboard` to this line: https://github.com/thoughtbot/liftoff/blob/master/lib/liftoff/project_builder.rb#L91

**Comment by gfontenot** [comment]
Huh, weird. Never run into this myself. Your assumption about where the fix should go is spot on.

**Comment by jakecraige** [comment]
@marcelofabri Are you interested in opening a PR for this change?

**Comment by gfontenot** [comment]
This is fixed with #238
