### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Limeberg** [thoughtbot/liftoff#232]
When do you plan on releasing the next version since you now have added Carthage support?

**Comment by gfontenot** [comment]
Hey, sorry for the delay here. We want to try to get the two remaining PRs in, as well as fixing the underlying issues behind #192. Once those are done, we should cut a release.

**Comment by priteshshah1983** [comment]
+1

**Comment by gfontenot** [comment]
I'm going to try to cut a release today.

**Comment by gfontenot** [comment]
Actually, there are a couple of things that I think we need to get fixed before releasing the next version. I'm tracking them in the 1.6.0 milestone.

**Comment by gfontenot** [comment]
1.6 has been released :tada: 

Sorry for the delay :disappointed:
