### ISSUE TITLE
Set release "Installation Directory" to `/Applications`

### ISSUE THREAD

**Issue by jakecraige** [thoughtbot/liftoff#235]
Fixes an issue where xcode builds generic xcode archives instead of iOS app archives

http://stackoverflow.com/a/30921685/1720355

**Comment by gfontenot** [comment]
Is this a thing that still needs to happen?

**Comment by jakecraige** [comment]
Yeah, I think we actually need to _not_ set it in this project. It causes a super weird error so it would be best to prevent it.

**Comment by jakecraige** [comment]
Here's where I fixed it in Tropos https://github.com/thoughtbot/Tropos/pull/155

**Comment by gfontenot** [comment]
Cool, we could just delete that key as part of our project setup.

**Comment by marcelofabri** [comment]
This can be closed now that #245 is merged.
