### ISSUE TITLE
Xcode 7.1 

### ISSUE THREAD

**Issue by Gladkov-Art** [thoughtbot/liftoff#250]
It appears that in Xcode 7.1 liftoff creates project and puts Main.storyboard and LaunchScreen.xib to the "Compile sources" phase. This behavior leads to compile error. Moving storyboard and xib to "Copy Bundle Resources" phase solves the problem. 
There is a discussion on apple's developer portal https://forums.developer.apple.com/thread/18369

**Comment by marcelofabri** [comment]
This is fixed on `master`, but a release with this change wasn't made yet. (#238)

**Comment by gfontenot** [comment]
Yeah, sorry. Been really negligent on this. I'll see what I can do to get a release out this week.

**Comment by Gladkov-Art** [comment]
Thanks a lot!

**Comment by jakecraige** [comment]
[1.6 is now out](https://github.com/thoughtbot/liftoff/releases/tag/1.6.0) which resolves this.
