### ISSUE TITLE
Liftoff not compatible with Cocoapods v1.0.0

### ISSUE THREAD

**Issue by mathmatrix828** [thoughtbot/liftoff#267]
Note

- :exclusive => true is no longer supported
- link_with is now abstract_target

As per Cocoapods v1.0.0 [Podfile](https://guides.cocoapods.org/syntax/podfile.html#abstract_target)

**Comment by gfontenot** [comment]
Thanks for the report! I don't suppose you'd be willing to open a PR to [update the default Podfile](https://github.com/thoughtbot/liftoff/blob/master/templates/Podfile)?

**Comment by mathmatrix828** [comment]
Just did! #268

**Comment by gfontenot** [comment]
Fixed in #268
