### ISSUE TITLE
add some compile option

### ISSUE THREAD

**Issue by lmule** [thoughtbot/liftoff#270]
hi 
    if i want to add some compile option such as 'GCC_PRECOMPILE_PREFIX_HEADER' ,where can i add into the ~/.liftoffrc? or what can i do?
    thank u very much  ^_^

**Comment by marcelofabri** [comment]
You can use the `extra_config` key. Check `man liftoffrc` for more info

**Comment by lmule** [comment]
hi 
i found the key, and i add

```
extra_config:
  all:
    GCC_PRECOMPILE_PREFIX_HEADER:
      - YES
```
and project.pbxproj will show 
`GCC_PRECOMPILE_PREFIX_HEADER = 1;` 
not 
`GCC_PRECOMPILE_PREFIX_HEADER = YES;`
Then the 
![image](https://cloud.githubusercontent.com/assets/10286518/15532485/a6f187f2-2292-11e6-9ab4-e2981571d597.png)
will be "NO"

but if i change "YES" to another string "abc", then the project.pbxproj will show `GCC_PRECOMPILE_PREFIX_HEADER = abc;`
so, values in **extra_config** can't be BOOL?

**Comment by gfontenot** [comment]
the values you're seeing in the plist aren't actually booleans. They are literal `"YES"` and `"NO"` strings. Try wrapping `YES` in quotes.

**Comment by lmule** [comment]
that's it
thanks @marcelofabri @gfontenot
