### ISSUE TITLE
copy from existed configuration or target/scheme

### ISSUE THREAD

**Issue by lmule** [thoughtbot/liftoff#272]
I want to add a configuration such as 'adhoc' or 'appstore' or a target like this.
Does liftoff has the feature of copying from the existed one?
just like the [https://github.com/krzysztofzablocki/KZBootstrap](url) does, you can search  **duplicate_configurations** on the page.

**Comment by gfontenot** [comment]
@lmule you opened and closed two of these issues. Did you have a question, or were you able to resolve the issue yourself?
