### ISSUE TITLE
Default Breakpoints

### ISSUE THREAD

**Issue by mergesort** [thoughtbot/liftoff#280]
Hi there. 

I realized that every time I start a new project, I add a few default breakpoints, like catching all Objective-C breakpoints, and ones for autolayout.

I was wondering if it'd be possible to add default breakpoints via liftoff into the xcodeproj.

Thanks a lot!

**Comment by OdNairy** [comment]
@mergesort Do you know that you can move this breakpoints to `User` scope? Then you will get your breakpoints in each project you open.

**Comment by mergesort** [comment]
I had no idea about that, that sounds amazing. Do you happen to have some documentation, or a place to point me to for that? I'm away from a computer for the next few days and would love to find a way to look into that.

Either way, than you very much, that's a great tip to know!

**Comment by OdNairy** [comment]
You can find info about it in this article:  
https://www.natashatherobot.com/xcode-debugging-user-breakpoints/
--  
Sincerely,  
Roman Gardukevich

**Comment by mergesort** [comment]
Thanks so much! I'll close this issue out.
